### ISSUE TITLE
Document behavior when adding or overwriting

### ISSUE THREAD

**Issue by thomp** [10sr/pack-el#7]
With an existing archive `testing123.zip`, if I mark a file `xyz.txt` currently not in the archive and then execute `pack-dired-do-pack`, specifying `testing123.zip` as the target, `xyz.txt` is added to the `testing123.zip` archive. This is the expected behavior, from my perspective.

If I perform the analogous steps with `testing123.tar.gz`, the `testing123.tar.gz` archive file is populated only with `xyz.txt` after the operation is complete. The files formerly archived in `testing123.tar.gz` are no longer in the archive.

Suggestions:

1. provide the user will the opportunity to be warned prior to overwriting a file or removing file(s) from an archive (at the minimum, make the warning an option/configurable -- e.g., with `pack-warn-before-overwrite-p` or something along those lines)

2. the behavior will be consistent across archive/compression formats. From my perspective, it seems desirable to have a file added to a tar.gz archive in the same manner as a zip archive. If not, perhaps this should be documented for the end-user.

**Comment by 10sr** [comment]
Thanks!
I was not aware of that behavior of zip archives...

**Comment by 10sr** [comment]
I updated so that now `:pack-append` command can be defined in `pack-program-alist`.
I separated this from `:pack` command because `tar` uses different command for creating new archives and appending to existing archives.
`pack-pack` command now simply fails when the target archive file already exists and no `:pack-append` command is defined.
